---
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /install/action.yml
    schedule:
      interval: daily
    commit-message:
      prefix: deps
    labels:
      - dependencies
    cooldown:
      default-days: 7